{{ $dockerTag := "commit-" + .Values.sha }}
{{ $configFile := .Files.Get "config.yaml" | fromYaml }}
{{ $namespace := .Values.namespace }}
{{ $backendHost := .Values.disableBackend | ternary
    "http://host.k3d.internal:8079"
    "http://pathoplexus-backend-service:8079"
}}

{{- if not .Values.disablePreprocessing }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pathoplexus-preprocessing
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pathoplexus
      component: pathoplexus-preprocessing
  template:
    metadata:
      labels:
        app: pathoplexus
        component: pathoplexus-preprocessing
    spec:
      containers:
        {{- range $key, $_ := $configFile.instances }}
        - name: preprocessing-{{ $key }}
          image: ghcr.io/pathoplexus/preprocessing-dummy:{{ $dockerTag }}
          imagePullPolicy: Always
          args:
            - "--watch"
            - "--backend-host={{ $backendHost }}/{{ $key }}"
        {{- end }}
      imagePullSecrets:
        - name: ghcr-secret
{{- end }}
