{{- if ne .Values.mode "e2e" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  namespace: {{ .Values.namespace }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: github-access-token
spec:
  encryptedData:
    token: AgA2A6LomYYfFsxEctEQNAVhz95u/mJcf/huzbQTTJjurcNyc6Du5jwTNPGaN4AKrRllOAzABbym09ZVP6xKWasYvKTo3QeFEuMyLuUSqJ2yKQGxku4gCV5dzxkh5V13pVz3cqVV92FzboOC83Qw/m/vIxOrf4ptVv5ZLF+0bzAbmBQZmzAgiAllKkegWyYLVlx1hK350CLSvXVQeRBVpcSNC/+Unr354qxUeT6KTx0ji278oVBHCh16RLnkx2koCx8Ub7C/JQoXrbSU7vNyxmmuNTGciFJ3I3nyW0dERnCdrBvoavvG0nx1hRVSsVJOWVWsYCRM00WEBGw6XLGE9ow7XVQ8KVD5i3zdjka59ORE1z80F5SFyEAqQ1saW3Tmt2UdRNnfQG1x+PmcSYoY8SBnYWzkzDBASz47K9g98uNnCSyP9JUQAgcflmCrqddtmXgb+QiHYJHi/r162ToAUhgZluVBlr7UBkgx/4NYBpIQMz0bYNpAQubLf1SGCU8sDMuyCj6potohxaRjUUui9vEdHaRtud+Qr21cDDJdE77IdWH+sN+NkxlpUti149rtl4equRNq0uqtDLE4FUfoXsSa+LdyduovZzuvHj5u4vG9aGfRTPBfN7kp6At25HA1On2KMe6DFWShub+ul7rcaOcOzwOyZSE4Pro3kyOciwFjV6GXer++FzR2gSlJpxSvgDIijhGc0s39L4eTzj4pQf3LwogM37VQvDtcZqliEL+b3fJaVOyPIc0Bf+cqS/0T23tyr5LtuZ1lkeYDj9v6edZNdAXlZhfjo5DCIweDeJYDW1rHLT9/VYPMXp3XZeY=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: github-access-token

{{- end }}