backend_url: http://localhost:8079/
keycloak_token_url: http://localhost:8083/realms/loculus/protocol/openid-connect/token
db_username: postgres
db_password: unsecure
db_url: "jdbc:postgresql://127.0.0.1:5432/loculus"
is_broker: False
organisms:
  cchf:
    ingest:
      nextclade_dataset_name: nextstrain/cchfv/linked
      nextclade_dataset_server: https://raw.githubusercontent.com/nextstrain/nextclade_data/cornelius-cchfv/data_output
      nucleotide_sequences:
        - L
        - M
        - S
      taxon_id: 3052518
      scientific_name: "Orthonairovirus haemorrhagiae"
      molecule_type: "genomic RNA"
    organismName: "Crimean-Congo Hemorrhagic Fever Virus"
    externalMetadata:
      - externalMetadataUpdater: ena
        name: ncbiReleaseDate
        type: date
      - externalMetadataUpdater: ena
        name: ncbiUpdateDate_L
        type: date
      - externalMetadataUpdater: ena
        name: ncbiUpdateDate_M
        type: date
      - externalMetadataUpdater: ena
        name: ncbiUpdateDate_S
        type: date
      - externalMetadataUpdater: ena
        name: ncbiSubmitterCountry
        type: string
      - externalMetadataUpdater: ena
        name: insdcAccessionBase_L
        type: string
      - externalMetadataUpdater: ena
        name: insdcAccessionBase_M
        type: string
      - externalMetadataUpdater: ena
        name: insdcAccessionBase_S
        type: string
      - externalMetadataUpdater: ena
        name: insdcVersion_L
        type: int
      - externalMetadataUpdater: ena
        name: insdcVersion_M
        type: int
      - externalMetadataUpdater: ena
        name: insdcVersion_S
        type: int
      - externalMetadataUpdater: ena
        name: insdcAccessionFull_L
        type: string
      - externalMetadataUpdater: ena
        name: insdcAccessionFull_M
        type: string
      - externalMetadataUpdater: ena
        name: insdcAccessionFull_S
        type: string
      - externalMetadataUpdater: ena
        name: bioprojectAccession
        type: string
      - externalMetadataUpdater: ena
        name: biosampleAccession
        type: string
      - externalMetadataUpdater: ena
        name: ncbiSourceDb
        type: string
      - externalMetadataUpdater: ena
        name: ncbiVirusName
        type: string
      - externalMetadataUpdater: ena
        name: ncbiVirusTaxId
        type: int
      - externalMetadataUpdater: ena
        name: sraRunAccession
        type: string
  ebola-zaire:
    ingest:
      taxon_id: 186538
      scientific_name: "Orthoebolavirus zairense"
      molecule_type: "genomic RNA"
    organismName: "Ebola Zaire"
    externalMetadata:
      - externalMetadataUpdater: ena
        name: ncbiReleaseDate
        type: date
      - externalMetadataUpdater: ena
        name: ncbiUpdateDate
        type: date
      - externalMetadataUpdater: ena
        name: ncbiSubmitterCountry
        type: string
      - externalMetadataUpdater: ena
        name: insdcAccessionBase
        type: string
      - externalMetadataUpdater: ena
        name: insdcVersion
        type: int
      - externalMetadataUpdater: ena
        name: insdcAccessionFull
        type: string
      - externalMetadataUpdater: ena
        name: bioprojectAccession
        type: string
      - externalMetadataUpdater: ena
        name: biosampleAccession
        type: string
      - externalMetadataUpdater: ena
        name: ncbiSourceDb
        type: string
      - externalMetadataUpdater: ena
        name: ncbiVirusName
        type: string
      - externalMetadataUpdater: ena
        name: ncbiVirusTaxId
        type: int
      - externalMetadataUpdater: ena
        name: sraRunAccession
        type: string
  west-nile:
    ingest:
      scientific_name: "West Nile virus"
      taxon_id: 3048448
      molecule_type: "genomic RNA"
    organismName: "West Nile Virus"
    externalMetadata:
      - externalMetadataUpdater: ena
        name: ncbiReleaseDate
        type: date
      - externalMetadataUpdater: ena
        name: ncbiUpdateDate
        type: date
      - externalMetadataUpdater: ena
        name: ncbiSubmitterCountry
        type: string
      - externalMetadataUpdater: ena
        name: insdcAccessionBase
        type: string
      - externalMetadataUpdater: ena
        name: insdcVersion
        type: int
      - externalMetadataUpdater: ena
        name: insdcAccessionFull
        type: string
      - externalMetadataUpdater: ena
        name: bioprojectAccession
        type: string
      - externalMetadataUpdater: ena
        name: biosampleAccession
        type: string
      - externalMetadataUpdater: ena
        name: ncbiSourceDb
        type: string
      - externalMetadataUpdater: ena
        name: ncbiVirusName
        type: string
      - externalMetadataUpdater: ena
        name: ncbiVirusTaxId
        type: int
      - externalMetadataUpdater: ena
        name: sraRunAccession
        type: string
