repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.14.2
  hooks:
    # Run the linter and fix issues.
    - id: ruff-check
      args: [ --fix ]
      files: ^ena-submission/
    # Run lint but only fix auto-fixable issues.
    - id: ruff-check
      args: [ --fix-only ]
      files: ^preprocessing/nextclade/
    # Run the formatter.
    - id: ruff-format
      files: ^ena-submission/|^preprocessing/nextclade/
- repo: local
  hooks:
    - id: prettier-values-schema
      name: prettier (values.schema.json)
      entry: npx prettier@3.6.2 --write
      language: system
      files: ^kubernetes/loculus/values\.schema\.json$
