name: loculus-ingest
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  # Core Python dependencies
  - python=3.12.9  # Pinned to 3.12.x series, check for patch updates within 3.12
  # Extra dependencies
  - biopython=1.85
  - click=8.3.0
  - curl=8.16.0
  - ijson=3.4.0.post0
  - jsonlines=4.0.0
  - ncbi-datasets-cli=18.9.0
  - nextclade=3.18.0
  - orjsonl=1.0.0
  - pandas=3.0.0
  - psycopg2=2.9.10
  - pytz=2025.2
  - PyYAML=6.0.3
  - requests=2.32.5
  - seqkit=2.10.1
  - snakefmt=0.11.2
  - snakemake=9.13.4
  - unzip=6.0
  - pytest=9.0.1
