name: loculus-ingest
channels:
  - conda-forge
  - bioconda
dependencies:
  # Core Python dependencies
  - python =3.12
  - pip >=24
  # Extra dependencies
  - biopython
  - click
  - ijson
  - jsonlines
  - ncbi-datasets-cli >=16.18.1
  - pandas
  - PyYAML
  - requests
  - seqkit
  - snakemake
  - unzip
