name: loculus-ingest
channels:
  - conda-forge
  - bioconda
dependencies:
  - python =3.12
  - pip >=24
  - ncbi-datasets-cli >=16.13.0
  - snakemake
  - pandas
  - PyYAML
  - click
  - requests
  - seqkit
  - unzip
  - biopython
