name: loculus-ingest
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  # Core Python dependencies
  - python=3.14.3  # Pinned to 3.12.x series, check for patch updates within 3.12
  # Extra dependencies
  - biopython=1.86
  - click=8.3.1
  - curl=8.18.0
  - ijson=3.5.0
  - jsonlines=4.0.0
  - ncbi-datasets-cli=18.18.0
  - nextclade=3.18.1
  - orjsonl=1.0.0
  - pandas=3.0.1
  - psycopg2=2.9.11
  - pytz=2025.2
  - PyYAML=6.0.3
  - requests=2.32.5
  - seqkit=2.13.0
  - snakefmt=0.11.4
  - snakemake=9.16.3
  - unzip=6.0
  - pytest=9.0.2
