name: loculus-ingest
channels:
  - conda-forge
  - bioconda
dependencies:
  # Core Python dependencies
  - python =3.12
  # Extra dependencies
  - biopython
  - click
  - ijson
  - jsonlines
  - ncbi-datasets-cli >=16.29.0
  - nextclade >=3.7.0
  - orjsonl
  - pandas
  - psycopg2
  - PyYAML
  - requests
  - seqkit
  - snakemake
  - tsv-utils
  - unzip
  - pycountry
  - fuzzywuzzy
