apiVersion: v1
kind: Service
metadata:
  name: website-{{ .Values.version }}-service
  namespace: preview
spec:
  type: ClusterIP
  selector:
    app: website-{{ .Values.version }}
  ports:
  - port: 3000
    name: http-port