# THIS FILE IS DEPLOYED MANUALLY, NEED TO FILL IN GITHUB PAT BELOW
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pp-preview
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - pullRequest:
        github:
          owner: pathoplexus
          labels:
            - preview
          repo: pathoplexus
          tokenRef:
            key: token
            secretName: github-token
        requeueAfterSeconds: 60
  template:
    metadata:
      name: 'pp-{{ (printf "%.25s" .branch) | replace "_" "-" }}-{{.number}}'
      annotations:
        argocd-image-updater.argoproj.io/image-list: 'backend=ghcr.io/pathoplexus/backend:{{.branch}} website=ghcr.io/pathoplexus/website:{{.branch}}'
        argocd-image-updater.argoproj.io/website.update-strategy: "digest"
        argocd-image-updater.argoproj.io/backend.update-strategy: "digest"
        argocd-image-updater.argoproj.io/website.pull-secret: "pullsecret:argocd/ghcr-secret"
        argocd-image-updater.argoproj.io/backend.pull-secret: "pullsecret:argocd/ghcr-secret"


    spec:
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'preview-{{ (printf "%.25s" .branch) | replace "_" "-" }}'
      project: default
      source:
        path: 'kubernetes/preview/'
        repoURL: 'https://github.com/pathoplexus/pathoplexus.git'
        targetRevision: '{{.branch}}'
        helm:
          parameters:
            - name: namespace
              value: 'preview-{{ (printf "%.25s" .branch) | replace "_" "-" }}'
            - name: version
              value: '{{.branch}}'
            - name: shortbranch
              value: '{{ (printf "%.25s" .branch) | replace "_" "-" }}'
            - name: branch
              value: '{{.branch}}'
            - name: host
              value: '{{ (printf "%.25s" .branch) | replace "_" "-" }}.preview.k3s.pathoplexus.org'


      syncPolicy:
        automated:
          selfHeal: true
