{{- $dockerTag := include "loculus.dockerTag" .Values }}
{{- $docsHost := printf "docs%s%s" .Values.subdomainSeparator .Values.host }}
{{- if .Values.previewDocs }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loculus-docs
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loculus
      component: docs
  template:
    metadata:
      labels:
        app: loculus
        component: docs
    spec:
      containers:
        - name: docs
          image: "ghcr.io/loculus-project/docs:{{ $dockerTag }}"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "200Mi"
              {{ include "loculus.standardCPURequest" $ }}
            limits:
              memory: "1Gi"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: loculus-docs
spec:
  selector:
    app: loculus
    component: docs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loculus-docs
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: {{ $docsHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loculus-docs
                port: 
                  number: 80
{{- end }}