{{- if or .Values.externalDatabase.urlSealedSecret .Values.keycloakDatabase.addrSealedSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: externaldb-credentials
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    {{- if .Values.externalDatabase.urlSealedSecret }}
    url: {{ .Values.externalDatabase.urlSealedSecret | quote }}
    username: {{ .Values.externalDatabase.usernameSealedSecret | quote }}
    password: {{ .Values.externalDatabase.passwordSealedSecret | quote }}
    {{- end }}
    {{- if .Values.keycloakDatabase.addrSealedSecret }}
    keycloak-db-addr: {{ .Values.keycloakDatabase.addrSealedSecret | quote }}
    keycloak-db-port: {{ .Values.keycloakDatabase.portSealedSecret | quote }}
    keycloak-db-database: {{ .Values.keycloakDatabase.databaseSealedSecret | quote }}
    keycloak-db-username: {{ .Values.keycloakDatabase.usernameSealedSecret | quote }}
    keycloak-db-password: {{ .Values.keycloakDatabase.passwordSealedSecret | quote }}
    {{- end }}
    {{- if .Values.crossRef.DOIPrefix }}
    crossref-doi-prefix: {{ .Values.crossRef.DOIPrefix | quote }}
    crossref-test-endpoint: {{ .Values.crossRef.testEndpoint | quote }}
    crossref-live-endpoint: {{ .Values.crossRef.liveEndpoint | quote }}
    crossref-username: {{ .Values.crossRef.usernameSealedSecret | quote }}
    crossref-test-password: {{ .Values.crossRef.testPasswordSealedSecret | quote }}
    crossref-live-password: {{ .Values.crossRef.livePasswordSealedSecret | quote }}
    {{- end }}
{{ end }}
