apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: compression-middleware
spec:
  compress: {}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-middleware
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
{{- if eq $.Values.environment "server" }}
{{- $backendHost := printf "backend-%s" .Values.host }}
{{- $keycloakHost := printf "authentication-%s" .Values.host }}
{{- $middlewareList := list (printf "%s-compression-middleware@kubernetescrd" $.Release.Namespace) }}
{{- if $.Values.enforceHTTPS }}
{{- $middlewareList = append $middlewareList (printf "%s-redirect-middleware@kubernetescrd" $.Release.Namespace) }}
{{- end }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loculus-website-ingress
  annotations:
    {{- if $.Values.enforceHTTPS }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    {{- end }}
    traefik.ingress.kubernetes.io/router.middlewares: "{{ join "," $middlewareList }}"
spec:
  rules:
    - host: "{{ .Values.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loculus-website-service
                port:
                  number: 3000
  tls:
  - hosts:
    - "{{ .Values.host }}"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loculus-backend-ingress
  annotations:
    {{- if $.Values.enforceHTTPS }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    {{- end }}
    traefik.ingress.kubernetes.io/router.middlewares: "{{ join "," $middlewareList }}"
spec:
  rules:
    - host: "{{ $backendHost }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loculus-backend-service
                port:
                  number: 8079
  tls:
  - hosts:
    - "{{ $backendHost }}"
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loculus-keycloak-ingress
  annotations:
    {{- if $.Values.enforceHTTPS }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    {{- end }}
    traefik.ingress.kubernetes.io/router.middlewares: "{{ join "," $middlewareList }}"
spec:
  rules:
    - host: "{{ $keycloakHost }}"
      http:
        paths:
          - path: /{+}
            pathType: Prefix
            backend:
              service:
                name: loculus-keycloak-service
                port:
                  number: 8083
  tls:
  - hosts:
    - "{{ $keycloakHost }}"
{{- end }}
