{{- if eq .Values.environment "server" }}
{{- $backendHost := printf "backend-%s" .Values.host }}
{{- $keycloakHost := printf "authentication-%s" .Values.host }}

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: loculus-website-ingressroute
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    link.argocd.argoproj.io/external-link: https://{{ .Values.host }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.host }}`)
      priority: 10
      services:
        - name: loculus-website-service
          port: 3000
  tls:
    certResolver: myresolver
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: loculus-backend-ingressroute
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ $backendHost }}`)
      priority: 10
      services:
        - name: loculus-backend-service
          port: 8079
  tls:
    certResolver: myresolver
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: loculus-keycloak-ingressroute
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ $keycloakHost }}`)
      priority: 10
      services:
        - name: loculus-keycloak-service
          port: 8083
  tls:
    certResolver: myresolver
{{- end}}
