{{- $traefikApiVersion := ternary "traefik.io/v1alpha1" "traefik.containo.us/v1alpha1" (eq (int $.Values.traefikVersion) 3) -}}
apiVersion: {{ $traefikApiVersion }}
kind: Middleware
metadata:
  name: compression-middleware
spec:
  compress: {}
---
apiVersion: {{ $traefikApiVersion }}
kind: Middleware
metadata:
  name: redirect-middleware
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{ if $.Values.secrets.basicauth }}
---
apiVersion: {{ $traefikApiVersion }}
kind: Middleware
metadata:
  name: basic-auth
spec:
  basicAuth:
    secret: basicauth
{{ end  }}
{{ if $.Values.robotsNoindexHeader }}
---
apiVersion: {{ $traefikApiVersion }}
kind: Middleware
metadata:
  name: noindex-robots-header
spec:
  headers:
    customResponseHeaders:
      X-Robots-Tag: "noindex, nofollow"
{{ end }}
---
apiVersion: {{ $traefikApiVersion }}
kind: Middleware
metadata:
  name: redirect-www-middleware
spec:
  redirectRegex:
    regex: "^https://www\\.(.*)"
    replacement: "https://$1"
    permanent: true
---
{{- if eq $.Values.environment "server" }}
{{- $backendHost := printf "backend%s%s" .Values.subdomainSeparator .Values.host }}
{{- $keycloakHost := (printf "authentication%s%s" $.Values.subdomainSeparator $.Values.host) }}
{{- $minioHost := (printf "s3%s%s" $.Values.subdomainSeparator $.Values.host) }}
{{- $middlewareList := list (printf "%s-compression-middleware@kubernetescrd" $.Release.Namespace) }}
{{- if $.Values.enforceHTTPS }}
{{- $middlewareList = append $middlewareList (printf "%s-redirect-middleware@kubernetescrd" $.Release.Namespace) }}
{{- end }}
{{ if $.Values.robotsNoindexHeader }}
{{ $middlewareList = append $middlewareList (printf "%s-noindex-robots-header@kubernetescrd" $.Release.Namespace) }}
{{ end }}

{{ $middlewareListForWebsite := $middlewareList }}
{{ $middlewareListForKeycloak := $middlewareList }}

{{ if $.Values.secrets.basicauth }}
{{ $middlewareListForWebsite = append $middlewareListForWebsite (printf "%s-basic-auth@kubernetescrd" $.Release.Namespace) }}
{{ $middlewareListForKeycloak = append $middlewareListForKeycloak (printf "%s-basic-auth@kubernetescrd" $.Release.Namespace) }}
{{ end }}

{{ $middlewareListForWebsite = append $middlewareListForWebsite (printf "%s-redirect-www-middleware@kubernetescrd" $.Release.Namespace) }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loculus-website-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "{{ join "," $middlewareListForWebsite }}"
    {{- if $.Values.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ $.Values.clusterIssuer | quote }}
    {{- end }}
spec:
  rules:
    - host: "{{ .Values.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loculus-website-service
                port:
                  number: 3000
    - host: "www.{{ .Values.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loculus-website-service
                port:
                  number: 3000
  tls:
  - hosts:
    - "{{ .Values.host }}"
    - "www.{{ .Values.host }}"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loculus-backend-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "{{ join "," $middlewareList }}"
    {{- if $.Values.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ $.Values.clusterIssuer | quote }}
    {{- end }}
spec:
  rules:
    - host: "{{ $backendHost }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loculus-backend-service
                port:
                  number: 8079
  tls:
  - hosts:
    - "{{ $backendHost }}"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loculus-keycloak-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "{{ join "," $middlewareListForKeycloak }}"
    {{- if $.Values.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ $.Values.clusterIssuer | quote }}
    {{- end }}
spec:
  rules:
    - host: "{{ $keycloakHost }}"
      http:
        paths:
          - path: /{+}
            pathType: Prefix
            backend:
              service:
                name: loculus-keycloak-service
                port:
                  number: 8083
  tls:
  - hosts:
    - "{{ $keycloakHost }}"
---
{{- if and .Values.s3.enabled .Values.runDevelopmentS3 }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "{{ join "," $middlewareList }}"
    {{- if $.Values.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ $.Values.clusterIssuer | quote }}
    {{- end }}
spec:
  rules:
    - host: "{{ $minioHost }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loculus-minio-service
                port:
                  number: 8084
  tls:
    - hosts:
        - "{{ $minioHost }}"
{{- end }}
{{- end }}
