{{- if eq .Values.environment "server" }}
{{- $backendHost := printf "backend-%s" .Values.host }}
{{- $keycloakHost := printf "authentication-%s" .Values.host }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loculus-website-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: "{{ .Values.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loculus-website-service
                port:
                  number: 3000
  tls:
  - hosts:
    - "{{ .Values.host }}"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loculus-backend-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: "{{ $backendHost }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loculus-backend-service
                port:
                  number: {{ $backendHost }}
  tls:
  - hosts:
    - "{{ $backendHost }}"
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loculus-keycloak-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: "{{ $keycloakHost }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loculus-keycloak-service
                port:
                  number: 8083
  tls:
  - hosts:
    - "{{ $keycloakHost }}"
{{- end}}
