{{- range $key, $organism := (include "loculus.enabledOrganisms" . | fromJson) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: loculus-lapis-{{ $key }}-pdb
spec:
  maxUnavailable: {{ $.Values.pdb.lapis.maxUnavailable | default 1 }}
  selector:
    matchLabels:
      app: loculus
      component: lapis-{{ $key }}
{{- end }}
